### ISSUE TITLE
Doesn't Work Properly

### ISSUE THREAD

**Issue by Roroca-1** [valleyofdoom/service-list-builder#1]
Traceback (most recent call last):
  File "main.py", line 469, in <module>
  File "main.py", line 248, in main
  File "configparser.py", line 684, in read
  File "configparser.py", line 998, in _read
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 365: illegal multibyte sequence
[10540] Failed to execute script 'main' due to unhandled exception!

**Comment by valleyofdoom** [comment]
Can you show the config file?

**Comment by Roroca-1** [comment]
```
[enabled_services]

AudioEndpointBuilder

AudioSrv

Audiosrv

BrokerInfrastructure

CoreMessagingRegistrar

CryptSvc

DcomLaunch

gpsvc

LSM

MMCSS

msiserver

Power

ProfSvc

RpcEptMapper

RpcSs

sppsvc

TextInputManagementService

TrustedInstaller

UserManager

Winmgmt

camsvc

seclogon

StateRepository

BFE #加速器相关

WinHttpAutoProxySvc


[individual_disabled_services]

acpipagr

afunix

amdgpio2

AsyncMac

bam

Beep

bfs

bindflt

blbdrive

bowser

cdrom

CimFS

CldFlt

CLFS

clreg

CompositeBus

DfsC

discache

EhStorClass

fvevol

GPIOClx0101

GpuEnergyDrv

IntelPMT

iorate

kdnic

KSecPkg

lltdio

luafv

mpsdrv

mrxsmb

mrxsmb10

mrxsmb20

MSKSSRV

MsLldp

MsSecCore

MsSecFlt

MSTEE

NdisCap

NdisVirtualBus

NdisWan

Ndu

NetBIOS

NetBT

npsvctrig

PEAUTH

PptpMiniport

PRM

RasAgileVpn

Rasl2tp

RasPppoe

RasSstp

rdbss

rdpbus

RDPCDD

RDPENCDD

RDPREFMP

rdyboost

rspndr

secdrv

SgrmAgent

spaceport

srv

srv2

srvnet

storflt

storqosflt

tcpipreg

Telemetry

tunnel

UEFI

umbus

UnionFS

vdrvroot

Vid

wanarp

Wanarpv6

wcifs

WindowsTrustedRT

WindowsTrustedRTProxy

WmiAcpi

Wof

BasicDisplay  #安全模式、gpu驱动重启

VgaSave

FileCrypt #FACEIT

msisadrv #笔记本键盘 移动设备

#mssmbios #GTA5

#pcw #自带任务管理器

swenum #相机

tdx #Wi-Fi

vwififlt #Wi-Fi

volmgrx #Raid

volsnap #win8-

WlanSvc #Wi-Fi

#Dhcp #Wi-Fi, 魔法工具自动配置proxy

#WinHttpAutoProxySvc #魔法工具自动配置proxy

EventLog #Wi-Fi

Netman #Wi-Fi

netprofm #Win11任务栏, Wi-Fi

NetSetupSvc #Wi-Fi

NlaSvc #Wi-Fi

nsi #Win11任务栏, Wi-Fi, Apex Legends, Valorant, Uplay

Wcmsvc #Wi-Fi

Appinfo #UAC

AppXSvc #Win10 1803, Win11

#hidserv #多媒体键

PlugPlay #Win7

tiledatamodelsvc #Win10 1607

UdkUserSvc #Windows默认开始菜单

acpitime

monitor #自带色彩管理 某些游戏显示器识别配置



[rename_binaries]

C:\Windows\System32\backgroundTaskHost.exe

C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe

C:\Windows\SystemApps\Microsoft.Windows.Search_cw5n1h2txyewy\SearchApp.exe

C:\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\TextInputHost.exe

C:\Windows\System32\RuntimeBroker.exe # Windows 默认开始菜单

C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe # Windows 默认开始菜单

C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartMenuExperienceHost.exe # Windows 默认开始菜单

C:\Windows\helppane.exe
```

**Comment by valleyofdoom** [comment]
Removing the comments with special characters fixes the issue. Alternatively, write the comments in English.
