### ISSUE TITLE
"Failed to execute script 'main' due to unhandled exception!"

### ISSUE THREAD

**Issue by AGMAST3R** [valleyofdoom/service-list-builder#3]
been getting this error not sure whats wrong:

> [CLI] INFO: item does not exist: \Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\TextInputHost.exe... skipping
> [CLI] INFO: item does not exist: \Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe... skipping
> Traceback (most recent call last):
>   File "main.py", line 469, in <module>
>   File "main.py", line 410, in main
> AttributeError: 'str' object has no attribute 'copy'
> [4536] Failed to execute script 'main' due to unhandled exception!

uncommenting the ones mentioned in the start leaves me with this:

> Traceback (most recent call last):
>   File "main.py", line 469, in <module>
>   File "main.py", line 410, in main
> AttributeError: 'str' object has no attribute 'copy'
> [764] Failed to execute script 'main' due to unhandled exception!
> 

heres my config aswell:

> **[enabled_services]**
> vgc
> AppIdSvc
> AudioEndpointBuilder
> Audiosrv
> BrokerInfrastructure
> CoreMessagingRegistrar
> CryptSvc
> DcomLaunch
> gpsvc
> LSM
> MMCSS
> msiserver
> Power
> ProfSvc
> RpcEptMapper
> RpcSs
> sppsvc
> TextInputManagementService
> TrustedInstaller
> UserManager
> Winmgmt
> #WlanSvc 
> #Dhcp 
> #EventLog 
> #Netman 
> #netprofm 
> #NetSetupSvc 
> #NlaSvc 
> #nsi 
> #Wcmsvc 
> #Appinfo 
> #AppXSvc 
> camsvc 
> #FrameServerMonitor 
> #SystemEventsBroker 
> #hidserv 
> #PlugPlay 
> #seclogon 
> StateRepository 
> #tiledatamodelsvc 
> #UdkUserSvc 
> 
> **[individual_disabled_services]**
> acpipagr
> afunix
> amdgpio2
> AsyncMac
> bam
> Beep
> bfs
> bindflt
> blbdrive
> bowser
> cdrom
> CimFS
> CldFlt
> CLFS
> clreg
> CompositeBus
> DfsC
> discache
> EhStorClass
> fvevol
> GPIOClx0101
> GpuEnergyDrv
> IntelPMT
> iorate
> kdnic
> KSecPkg
> ksthunk
> lltdio
> luafv
> mpsdrv
> mrxsmb
> mrxsmb10
> mrxsmb20
> MsLldp
> MsSecCore
> MsSecFlt
> MSTEE
> NdisCap
> NdisVirtualBus
> NdisWan
> Ndu
> NetBIOS
> NetBT
> npsvctrig
> PEAUTH
> PptpMiniport
> PRM
> RasAgileVpn
> Rasl2tp
> RasPppoe
> RasSstp
> rdbss
> rdpbus
> RDPCDD
> RDPENCDD
> RDPREFMP
> rdyboost
> rspndr
> secdrv
> SgrmAgent
> spaceport
> srv
> srv2
> srvnet
> storflt
> storqosflt
> tcpipreg
> Telemetry
> tunnel
> UEFI
> umbus
> UnionFS
> vdrvroot
> Vid
> wanarp
> Wanarpv6
> wcifs
> WindowsTrustedRT
> WindowsTrustedRTProxy
> WmiAcpi
> Wof
> .# ahcache 
> .# BasicDisplay  
> .# VgaSave 
> FileCrypt 
> msisadrv 
> .# mssmbios 
> pcw 
> .# Psched 
> MSKSSRV 
> .# swenum 
> tdx 
> vwififlt 
> volsnap 
> 
> **[rename_binaries]**
> \Windows\System32\backgroundTaskHost.exe
> \Windows\System32\ctfmon.exe
> .#\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
> \Windows\SystemApps\Microsoft.Windows.Search_cw5n1h2txyewy\SearchApp.exe
> .#\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\TextInputHost.exe
> \Windows\System32\RuntimeBroker.exe
> \Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe
> \Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartMenuExperienceHost.exe

**Comment by valleyofdoom** [comment]
A lower/upper filter in registry is the wrong type (REG_SZ) on your OS. Everyone that has this problem was a result of the user causing this, it is supposed to be a REG_MULTI_SZ as per a stock Windows installation.

The "item does not exist" messages are not errors, they are just telling you that the tool can't rename something that doesn't exist.

Unrelated to the error but this is invalid syntax ``.#``.

**Comment by AGMAST3R** [comment]
interesting thank you, how could i go about finding the scuffed lower/upper filter, would looking through all services one by one to find which one is REG_SZ rather than REG_MULTI_SZ work?
the .# was done for formatting reasons

**Comment by AGMAST3R** [comment]
also I assume the thread can be closed since its user error and not related to the program itself

**Comment by valleyofdoom** [comment]
CTRL + F "UpperFilters" and "LowerFilters" in ``HKLM\SYSTEM\CurrentControlSet\Control\Class`` and check the type of each key.

That should be something like ``reg query "HKLM\SYSTEM\CurrentControlSet\Control\Class" /s /v "UpperFilters"`` and ``reg query "HKLM\SYSTEM\CurrentControlSet\Control\Class" /s /v "LoweFilters"`` in CMD. I'm on Linux right now so can't see if I'm remembering the correct syntax.
